export const url = "https://chat.izk-arcos.nl/";
export const url2 = "http://127.0.0.1:8080"
export const loginurl = url+"login";
export const userinforetrieval = url+"tokenlogin";
export const getmsgs = url+"getmsgs";
export const sendmsg = url+"sendmsg";
export const version = '0.2.0p'
export const autoUpdateString = "AutoUpdate is not enabled for this build."
export const errorOnLogin = true
export const loginErrorString = autoUpdateString